const STORE='clock_project_folio_v1';
const CARDS=[
['brief','Project Brief and Success Criteria','Show that you understand what the free-standing timber Clock must achieve.','Verified requirements, constraints and a checklist linking practical quality with evidence.','What must your Clock do and show to be considered successful?',['My Clock must…','I will judge the finished Clock by…'],'Clock silhouette surrounded by function, accuracy, appearance, safety and evidence criteria.'],
['plans','Plans, Dimensions and Cutting List','Explain how the supplied drawing and written dimensions control the project.','Plan reading, written millimetre dimensions, component schedule, quantities and material calculations.','How did the drawing prevent a measuring or cutting error?',['The written drawing shows…','I checked this dimension by…'],'Supplied Clock views with dimension lines leading to a checked cutting list.'],
['whs','WHS, WMS and Drill Press SOP','Show how hazards were managed through the actual Clock work sequence.','WMS stages, hazards, hierarchy of controls, school SOP references and appropriate PPE.','Which Clock hazard required the strongest control, and why?',['The hazard was…','The higher-order control was…'],'Clock work sequence beside the hierarchy of controls and an SOP checkpoint.'],
['timber','Timber Inspection and Responsible Selection','Record how grain, defects, stability and responsible use affected material placement.','Annotated timber, placement decisions, rejected faults, off-cut opportunities and timber-source notes.','How did inspecting the timber improve quality or reduce waste?',['I selected this piece because…','I avoided or repositioned…'],'Timber board labelled with grain, defect, usable area and approved Clock component.'],
['carcass','Carcass, Rebates and Chamfers','Explain how the Clock body was formed accurately and checked before assembly.','Rebate layout and fit, chamfer consistency, dry fitting, clamps and squareness checks.','Which check had the greatest effect on the carcass quality?',['Before assembly, I checked…','The rebate or chamfer was successful because…'],'Exploded Clock carcass with rebate shoulders, chamfered edges and clamp checks.'],
['opening','Clock Face Opening and Mechanism','Show how the face opening and supplied battery mechanism were planned, fitted and tested.','Marked opening, approved machine setup evidence, alignment, clearance and functional mechanism test.','What proved that the face opening and mechanism fit-up were accurate?',['The opening was located by…','The mechanism worked correctly when…'],'Clock face centre, secured drilling setup and aligned battery mechanism.'],
['drawer','Hidden Drawer and Off-cut Use','Record how the secret drawer was made from suitable off-cuts and fitted without forcing.','Off-cut selection, square assembly, gap checks, movement test and measured corrections.','How did you balance responsible reuse with a quality drawer fit?',['The off-cut was suitable because…','The drawer fit improved after…'],'Off-cut becoming a square hidden drawer with clearance and alignment checks.'],
['surface','Surface Preparation','Explain how sanding and inspection prepared the Clock for the approved finish.','Progressive surface preparation, scratch checks, edge protection, dust controls and ready-for-finish evidence.','What evidence showed the Clock was ready for oil?',['I inspected the surface by…','I knew the surface was ready when…'],'Magnified rough, scratched and oil-ready timber surfaces on the Clock.'],
['finish','Three-coat Oil Finish','Record each coat safely and explain the quality decision before the next coat.','Product label and SDS checks, coat records, safe handling, coverage observations and corrections.','How did checking between coats improve the final finish?',['The selected product required…','Before the next coat, I checked…'],'Three numbered finish stages with inspection notes and safe-work reminders.'],
['evidence','Photos, Captions and Project Evidence','Build a traceable evidence story instead of a scrapbook of final images.','Purposeful stage photos, captions, drawings, WMS, calculations and quality checkpoints.','Which item best proves a decision you made during construction?',['This evidence shows…','It matters because…'],'Timeline of planning, making, checking and explaining the Clock process.'],
['problems','Problem Solving and Improvement','Explain one genuine Clock fault, its likely cause, the check used and the measured correction.','Problem, diagnosis, teacher-approved action, before-and-after evidence and learning.','What problem produced the most useful improvement to your process?',['The symptom was…','I confirmed the cause by…','The approved correction was…'],'Problem → cause → check → correction → improved Clock result.'],
['evaluation','PMI Evaluation and Final Quality','Judge the completed Clock honestly against function, aesthetics, quality and the assessment brief.','Final Clock photos, drawer and mechanism tests, PMI evidence, limitations and one realistic improvement.','How successfully does your completed Clock meet the brief?',['A positive feature is…','A minus supported by evidence is…','An interesting finding was…'],'Final Clock with callouts for function, craftsmanship, finish, PMI and next improvement.']
].map((c,i)=>({id:i+1,key:c[0],title:c[1],purpose:c[2],evidence:c[3],prompt:c[4],starters:c[5],visual:c[6]}));
const $=id=>document.getElementById(id), enc=new TextEncoder(), dec=new TextDecoder();
const safe=s=>String(s||'clock-folio').trim().replace(/[^a-z0-9]+/gi,'-').replace(/^-+|-+$/g,'').toLowerCase()||'clock-folio';
const status=s=>$('folioStatus').textContent=s;
function cards(){ $('folioCards').innerHTML=CARDS.map(c=>`<article class="folio-card"><div class="folio-number">${c.id}<span>Card</span></div><div class="folio-body"><div class="folio-head"><div><p class="section-kicker">Evidence card ${c.id}</p><h2>${c.title}</h2></div><label class="folio-complete"><input type="checkbox" data-done="${c.key}"> Reviewed</label></div><div class="folio-meta"><article><h3>Why this matters</h3><p>${c.purpose}</p></article><article><h3>Evidence to collect</h3><p>${c.evidence}</p><h3>Visual idea</h3><p>${c.visual}</p></article></div><div class="folio-response-grid"><div class="folio-field"><label for="response-${c.key}">${c.prompt}</label><textarea id="response-${c.key}" data-response="${c.key}" placeholder="Write your response here…"></textarea></div><div class="folio-field"><label for="note-${c.key}">Evidence note or photo caption</label><textarea id="note-${c.key}" data-note="${c.key}" placeholder="What does your photo, sketch or check prove?"></textarea><details class="sentence-starters"><summary>Sentence starters</summary><ul>${c.starters.map(s=>`<li>${s}</li>`).join('')}</ul></details></div></div><div class="photo-panel"><h3>Add one useful photo</h3><p>Use your own build photo, sketch or check. It is included in the ZIP backup.</p><label class="photo-upload">Choose photo<input type="file" accept="image/*" data-photo="${c.key}"></label><img class="photo-preview" data-preview="${c.key}" alt="${c.title} evidence preview"></div></div></article>`).join(''); }
function session(){const r={},n={},d={},p={};CARDS.forEach(c=>{r[c.key]=$(`response-${c.key}`).value;n[c.key]=$(`note-${c.key}`).value;d[c.key]=document.querySelector(`[data-done="${c.key}"]`).checked;const i=document.querySelector(`[data-preview="${c.key}"]`);if(i.dataset.data)p[c.key]={name:i.dataset.name||`${c.key}.jpg`,data:i.dataset.data};});return{version:1,project:'Year 9 Timber Clock Project Folio',savedAt:new Date().toISOString(),student:{first:$('studentFirst').value,last:$('studentLast').value,className:$('studentClass').value,date:$('sessionDate').value},responses:r,notes:n,done:d,photos:p};}
function setPhoto(k,p){const i=document.querySelector(`[data-preview="${k}"]`);i.src=p.data;i.dataset.data=p.data;i.dataset.name=p.name||`${k}.jpg`;i.style.display='block';}
function apply(x){const s=x.student||{};$('studentFirst').value=s.first||'';$('studentLast').value=s.last||'';$('studentClass').value=s.className||'';$('sessionDate').value=s.date||'';CARDS.forEach(c=>{$(`response-${c.key}`).value=x.responses?.[c.key]||'';$(`note-${c.key}`).value=x.notes?.[c.key]||'';document.querySelector(`[data-done="${c.key}"]`).checked=!!x.done?.[c.key];if(x.photos?.[c.key])setPhoto(c.key,x.photos[c.key]);});save(false);status('Saved folio restored.');}
function progress(){const x=session(),done=CARDS.filter(c=>x.responses[c.key].trim()&&x.notes[c.key].trim()).length;$('progressCount').textContent=`${done} of ${CARDS.length} evidence cards complete`;$('progressBar').style.width=`${done/CARDS.length*100}%`;}
function save(show=true){localStorage.setItem(STORE,JSON.stringify(session()));progress();if(show)status(`Saved ${new Date().toLocaleTimeString()}.`);}
function compress(file){return new Promise((ok,bad)=>{const r=new FileReader();r.onerror=bad;r.onload=()=>{const im=new Image();im.onerror=bad;im.onload=()=>{const scale=Math.min(1,1400/Math.max(im.width,im.height)),can=document.createElement('canvas');can.width=Math.round(im.width*scale);can.height=Math.round(im.height*scale);can.getContext('2d').drawImage(im,0,0,can.width,can.height);ok({name:file.name.replace(/\.[^.]+$/,'.jpg'),data:can.toDataURL('image/jpeg',.82)});};im.src=r.result;};r.readAsDataURL(file);});}
function crc(b){let c=-1;for(let v of b){c^=v;for(let i=0;i<8;i++)c=(c>>>1)^(0xedb88320&-(c&1));}return(c^-1)>>>0;}function w16(a,o,v){a[o]=v&255;a[o+1]=v>>>8&255}function w32(a,o,v){a[o]=v&255;a[o+1]=v>>>8&255;a[o+2]=v>>>16&255;a[o+3]=v>>>24&255}function join(a){let n=a.reduce((x,y)=>x+y.length,0),r=new Uint8Array(n),o=0;a.forEach(x=>{r.set(x,o);o+=x.length});return r}
function zip(files){const l=[],c=[];let o=0;const now=new Date(),t=now.getHours()<<11|now.getMinutes()<<5|Math.floor(now.getSeconds()/2),d=now.getFullYear()-1980<<9|now.getMonth()+1<<5|now.getDate();files.forEach(f=>{const n=enc.encode(f.name),z=crc(f.bytes),h=new Uint8Array(30+n.length);w32(h,0,0x04034b50);w16(h,4,20);w16(h,10,t);w16(h,12,d);w32(h,14,z);w32(h,18,f.bytes.length);w32(h,22,f.bytes.length);w16(h,26,n.length);h.set(n,30);l.push(h,f.bytes);const q=new Uint8Array(46+n.length);w32(q,0,0x02014b50);w16(q,4,20);w16(q,6,20);w16(q,12,t);w16(q,14,d);w32(q,16,z);w32(q,20,f.bytes.length);w32(q,24,f.bytes.length);w16(q,28,n.length);w32(q,42,o);q.set(n,46);c.push(q);o+=h.length+f.bytes.length});const cd=join(c),end=new Uint8Array(22);w32(end,0,0x06054b50);w16(end,8,files.length);w16(end,10,files.length);w32(end,12,cd.length);w32(end,16,o);return join([...l,cd,end])}
function dl(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1200)}function b64(s){const raw=(s||'').split(',')[1]||'',bin=atob(raw);return Uint8Array.from(bin,x=>x.charCodeAt(0));}
function getZip(){const x=session(),f=[{name:'clock-folio-session.json',bytes:enc.encode(JSON.stringify(x,null,2))}];Object.entries(x.photos).forEach(([k,p])=>f.push({name:`photos/${k}-${p.name}`.replace(/[^\w./-]/g,'-'),bytes:b64(p.data)}));dl(new Blob([zip(f)],{type:'application/zip'}),`${safe(`${x.student.first}-${x.student.last}`)}-clock-folio-backup.zip`);status('ZIP backup downloaded with answers and photos.');}
const r16=(b,o)=>b[o]|b[o+1]<<8,r32=(b,o)=>(b[o]|b[o+1]<<8|b[o+2]<<16|b[o+3]<<24)>>>0;
async function restore(f){try{if(f.name.toLowerCase().endsWith('.json'))return apply(JSON.parse(await f.text()));const b=new Uint8Array(await f.arrayBuffer());let o=0,json='';while(o<b.length&&r32(b,o)===0x04034b50){const size=r32(b,o+18),ns=r16(b,o+26),ex=r16(b,o+28),start=o+30+ns+ex,name=dec.decode(b.slice(o+30,o+30+ns));if(r16(b,o+8)!==0)throw Error();if(name==='clock-folio-session.json')json=dec.decode(b.slice(start,start+size));o=start+size}if(!json)throw Error();apply(JSON.parse(json));}catch{status('Could not read that backup. Use a ZIP or JSON downloaded from this folio.');}}
function init(){cards();$('sessionDate').value=new Date().toISOString().slice(0,10);try{const s=localStorage.getItem(STORE);if(s)apply(JSON.parse(s));}catch{localStorage.removeItem(STORE)}progress();document.addEventListener('input',e=>{if(e.target.matches('input,textarea'))save()});document.addEventListener('change',async e=>{if(e.target.matches('[data-photo]')){const f=e.target.files[0];if(f){setPhoto(e.target.dataset.photo,await compress(f));save()}e.target.value=''}else save()});$('downloadZip').onclick=getZip;$('downloadJson').onclick=()=>{const x=session();dl(new Blob([JSON.stringify(x,null,2)],{type:'application/json'}),`${safe(`${x.student.first}-${x.student.last}`)}-clock-folio-session.json`);status('JSON session downloaded.')};$('restoreSession').onclick=()=>$('restoreInput').click();$('restoreInput').onchange=e=>{if(e.target.files[0])restore(e.target.files[0]);e.target.value=''};$('printFolio').onclick=()=>window.print();$('clearFolio').onclick=()=>{if(confirm('Clear all saved Clock folio work from this browser?')){localStorage.removeItem(STORE);location.reload()}}}document.addEventListener('DOMContentLoaded',init);
